blog/bike_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from bike_app.views import *

urlpatterns = [
    path("admin/", admin.site.urls),

    path('captcha/', include('captcha.urls')),
    path('', include('bike_app.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('api.v1.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns = [
                      path("__debug__/", include("debug_toolbar.urls")),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found
admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Посты"

blog/users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordChangeDoneView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from .views import *

app_name = 'users'


urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', Profile.as_view(), name='profile'),

    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view(template_name="users/password_reset_form.html",
                                   email_template_name='users/password_reset_email.html',
                                   success_url=reverse_lazy('users:password_reset_done')
                                   ),
         name='password_reset',
         ),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html", success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'
         ),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

    path('verify/<str:email>/<uuid:code>', EmailVerificationView.as_view(), name='email_verification'),
]

blog/templates/base.html
{% load static %}
{% load tags %}


<!DOCTYPE html>
<html>
<head>
    <title>{{title}}</title>

    <link type="text/css" href="{% static 'bike_app/css/styles.css' %}" rel="stylesheet"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="{% static 'bike_app/images/main.ico' %}" type="image/x-icon"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Настройки Bootstrap-->
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
            crossorigin="anonymous"
    />
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
            crossorigin="anonymous"
    ></script>


    <!-- Header -->
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">

    <div class="cotainer">
        <tr>
            <td valign=top>
                {% block mainmenu %}
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                    <div class="container-fluid">
                        <a class="navbar-brand p-0" href="{% url 'home' %}"><img
                                src="{% static 'bike_app/images/Bikes.png' %}" alt="Logo" width="75"></a>
                        <button
                                class="navbar-toggler"
                                type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#navbarNav"
                                aria-controls="navbarNav"
                                aria-expanded="false"
                                aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNav">
                            <div class="navbar-nav  me-auto">
                                {% for m in menu %}
                                <a class="nav-item nav-link" href="{% url m.url_name %}">{{m.title}}</a>
                                {% endfor %}
                            </div>
                            <div class="navbar-nav">
                                {% if request.user.is_authenticated %}
                                <a class="nav-link" href="{% url 'users:profile' %}">{{user.username}}</a>
                                <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                                {% else %}
                                <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
                                <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </nav>
                {% endblock mainmenu %}
                <!-- Конец header -->

                <table class="table-content" border=0 cellpadding="0" cellspacing="0">
                    <tr>
                        <!-- Sidebar слева -->
                        <td valign="top" class="left-chapters">

                            <ul id="leftchapters">
                                {% if cat_selected == 0 %}
                                <li class="selected">Все категории</li>
                                {% else %}
                                <li><a href="{% url 'home' %}">Все категории</a></li>
                                {% endif %}

                                {% show_categories cat_selected %}

                                <li>{% show_tags %}</li>

                            </ul>
                        </td>

                        <!-- Конец Sidebar'а -->

                        <td valign="top" class="content">
                            <!-- Свойства контента -->
                            {% block prop_content %}
                            {% include 'includes/messages.html' %}

                            {% endblock %}

                            <!-- Блок контента -->
                            <div class="content-text">

                                {% block content %}
                                {% endblock %}

                                {% if page_obj.has_other_pages %}

                                <ul class="pagination justify-content-center">
                                    {% if page_obj.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page=1">Первая</a>
                                    </li>
                                    <li>
                                        <a class="page-link"
                                           href="?page={{ page_obj.start_index }}">Предыдущая</a>
                                    </li>
                                    {% endif %}
                                    {% for p in paginator.page_range %}
                                    {% if page_obj.number == p %}
                                    <li class="page-item active"><a class="page-link">{{ p }}</a></li>
                                    {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                                    <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
                                    {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ paginator.num_pages }}">Последняя</a>
                                    </li>
                                    {% endif %}
                                </ul>
                                {% endif %}


                                <!--            <div class="pagination">-->
                                <!--    <span class="step-links">-->
                                <!--        {% if page_obj.has_previous %}-->
                                <!--            <a href="?page=1">&laquo; first</a>-->
                                <!--            <a href="?page={{ page_obj.previous_page_number }}">previous</a>-->
                                <!--        {% endif %}-->

                                <!--        <span class="current">-->
                                <!--            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.-->
                                <!--        </span>-->

                                <!--        {% if page_obj.has_next %}-->
                                <!--            <a href="?page={{ page_obj.next_page_number }}">next</a>-->
                                <!--            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>-->
                                <!--        {% endif %}-->
                                <!--    </span>-->
                                <!--</div>-->

                            </div>
                            <!-- Конец блока контента -->
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <!-- Footer -->
        <tr>
            <td valign=top>
                <footer class="bg-light text-center text-lg-start">
                    <!-- Copyright -->
                    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                        © 2020 Pet project
                    </div>
                    <!-- Copyright -->
                </footer>
            </td>
        </tr>
    </div>
</table>
<!-- Конец footer и страницы -->

</body>
</html>