blog/bike_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from bike_app.views import *

urlpatterns = [
    path("admin/", admin.site.urls),

    path('captcha/', include('captcha.urls')),
    path('', include('bike_app.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('api/', include('api.v1.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]
if settings.DEBUG:
    urlpatterns = [
                      path("__debug__/", include("debug_toolbar.urls")),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found
admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Посты"

blog/users/urls.py
from django.contrib.auth.views import (LogoutView, PasswordChangeDoneView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from .views import *

app_name = 'users'


urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', Profile.as_view(), name='profile'),

    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view(template_name="users/password_reset_form.html",
                                   email_template_name='users/password_reset_email.html',
                                   success_url=reverse_lazy('users:password_reset_done')
                                   ),
         name='password_reset',
         ),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html", success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'
         ),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

    path('verify/<str:email>/<uuid:code>', EmailVerificationView.as_view(), name='email_verification'),
]

blog/users/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from django.db import models
from django.urls import reverse
from django.utils.timezone import now

from users.utils import CustomStorage


class User(AbstractUser):
    """Расширенная модель User"""

    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True, null=True, verbose_name="Фотография", storage=CustomStorage())
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name="Дата рождения")
    is_verified_email = models.BooleanField(default=False)


class EmailVerification(models.Model):
    """Модель верификации пользователя чераз email"""

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    code = models.UUIDField(unique=True)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f'EmailVerification object for {self.user.email}'

    def send_verification_email(self) -> None:
        """Формирование письма для подтверждения учетной записи"""

        link = reverse('users:email_verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = self.request.build_absolute_uri(link)
        subject = f'Подтверждение учетной записи для {self.user.username}'
        message = f'Для подтверждения учетной записи для {self.user.email} перейдите по ссылке: {verification_link}'

        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.user.email],
            fail_silently=False,
        )

    def is_expired(self) -> bool:
        """Проверка на актуальность кода для верификации(срок службы 48 часов)"""

        return True if now() >= self.expiration else False

blog/users/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm,
                                       UserCreationForm)
from django.core.exceptions import ValidationError

from users.tasks import send_email_verification


class LoginUserForm(AuthenticationForm):
    """Форма авторизации пользователя"""

    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class RegisterUserForm(UserCreationForm):
    """Форма регистрации пользователя"""

    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))

    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')
        if any(char.isalpha() and not char.isascii() for char in password1):
            raise ValidationError('Пароль не должен содержать кириллицу.')
        return password1

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

    def clean_email(self) -> str:
        """Проверка email на уникальность"""

        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

    def save(self, commit=True) -> get_user_model():
        """Сохранение нового пользователя и отправка письма для подтверждения email с помощью Celery."""
        user = super(RegisterUserForm, self).save(commit=True)
        send_email_verification.delay(user.id)
        return user


class ProfileUserForm(forms.ModelForm):
    """Форма профайла пользователя"""

    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))
    this_year = datetime.date.today().year
    date_birth = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(this_year - 100, this_year - 18))))

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    """Форма изменения пароля пользователя"""

    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(
                                                                attrs={'class': 'form-input'}))

blog/users/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from .forms import (LoginUserForm, ProfileUserForm, RegisterUserForm,
                    UserPasswordChangeForm)
from .models import EmailVerification


class LoginUser(LoginView):
    """Класс представления страницы авторизации"""

    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}


class RegisterUser(CreateView):
    """Класс представления страницы регистрации"""

    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': "Регистрация"}
    success_url = reverse_lazy('users:login')


class Profile(LoginRequiredMixin, UpdateView):
    """Класс представления страницы профиля пользователя"""

    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': "Профиль пользователя", 'default_img': settings.DEFAULT_USER_IMAGE}

    def get_success_url(self) -> str:
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None) -> get_user_model():
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    """Класс представления для изменения пароля пользователя"""

    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"
    extra_context = {'title': "Изменение пароля"}


class EmailVerificationView(TemplateView):
    """Класс представления для подтверждения электронной почты"""

    title = 'Подтверждение электронной почты'
    template_name = 'users/email_verification_done.html'

    def get(self, request, *args, **kwargs) -> HttpResponseRedirect:
        code = kwargs['code']
        user = get_user_model().objects.get(email=kwargs['email'])
        email_verifications = EmailVerification.objects.filter(user=user, code=code)
        if email_verifications.exists() and not email_verifications.first().is_expired():
            user.is_verified_email = True
            user.save()
            return super(EmailVerificationView, self).get(request, *args, **kwargs)
        else:
            return redirect('users:login')

blog/users/templates/users/email_verification_done.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Адрес электронной почты подтвержден</h1>
 
<a href="{% url 'users:login' %}">Войти в профиль.</a>
{% endblock %}

blog/users/templates/users/login.html
{% extends 'base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
 
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Войти</button>

    <p ><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
<hr>
<p><a href="{% url 'social:begin' 'github' %}"><img src="/media/social_auth/github.png" width="50" height="50"></a></p>
</form>
 
{% endblock %}

blog/users/templates/users/password_change_done.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Пароль успешно изменен</h1>
 
<p >Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

blog/users/templates/users/password_change_form.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Изменение пароля</h1>
 
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
 
    <p ><button type="submit">Изменить пароль</button></p>
</form>
 
{% endblock %}

blog/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Пароль изменен</h1>
 
<p >Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>
 
{% endblock %}

blog/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<h1>Новый пароль</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p ><button type="submit">Сохранить</button></p>
</form>

{% endblock %}

blog/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>
<p >{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
<p >{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
{% endblock %}

blog/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

blog/users/templates/users/password_reset_form.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Восстановление пароля</h1>
 
<form method="post">
    {% csrf_token %}
{% for f in form %}
<p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}
 
    <p ><button type="submit">Сбросить по E-mail</button></p>
</form>
 
{% endblock %}

blog/users/templates/users/profile.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Профиль</h1>
 
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% if user.photo %}
    <p ><img src="{{ user.photo.url }}" width="250">
    {% else %}
    <p ><img src="{{ default_img }}" >
    {% endif %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
 
    <p ><button type="submit">Сохранить</button></p>
</form>
<hr>
<p ><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
 
{% endblock %}

blog/users/templates/users/register.html
{% extends 'base.html' %}
 
{% block content %}
<h1>{{title}}</h1>
 
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Регистрация</button>
</form>
 
{% endblock %}